### ISSUE TITLE
Setup question

### ISSUE THREAD

**Issue by ti0rafa** [peridot-php/peridot-concurrency#8]
Hello

I was testing `peridot-concurrency` but i can't seem to figure how to run multiple test files to produce something similar to the **after** screen shot you have on the main page. 

Im running peridot like so:

``` bash
app/vendor/bin/peridot -c app/config/peridot.php --concurrent --processes 5 projects/specs.php
```

Inside specs I'm including all the spec files I need.

**Comment by brianium** [comment]
@ti0rafa thanks for checking out the plugin.

Unfortunately, the plugin can't run suites concurrently from the same file (yet) - we are experimenting with some ways to do this in the 2.0 release of Peridot.

Right now it works at the file level, so if you have multiple files you want to run concurrently you can give it a directory containing specs. The suite loader is recursive so it should be able to find any spec files you have in the `projects/` directory:

```
$ app/vendor/bin/peridot -c app/config/peridot.php --concurrent --processes 5 projects/
```

You can also filter file patterns with the `--grep` switch.

```
$ app/vendor/bin/peridot -c app/config/peridot.php --grep "*.spec.php" --concurrent --processes 5 projects/
```

**Comment by ti0rafa** [comment]
@brianium thanks for the tip!

I did try setting up a directory like you mention. But I had a typo with their name, they were `*.specs.php` so they weren't pick by **Peridot**. But now it works like a _charm_.

I'm really looking forward to implement **Peridot** and **Leo** I like the overall idea behind it. Especially how I can customize it to fit my needs.

**Comment by brianium** [comment]
@ti0rafa great!

Thanks for your kind words. Keep an eye on development - we will be introducing a lot of great stuff in the 2.0 version.
